### ISSUE TITLE
Pause step definition timesout after 20000 seconds

### ISSUE THREAD

**Issue by id4automation** [inspiraller/cucumber-boilerplate-behind-corporate-network#1]
Hi , 

I am trying to use the predefined step "When I pause for 30000ms"  and it fails with the below error message.

> [chrome #0-0] function timed out after 20000 milliseconds
> [chrome #0-0] Error: function timed out after 20000 milliseconds
> [chrome #0-0]     at Timeout._onTimeout (~\node_modules\cucumber\lib\user_code_runner.js:91:22)
> [chrome #0-0]     at ontimeout (timers.js:475:11)
> [chrome #0-0]     at tryOnTimeout (timers.js:310:5)
> [chrome #0-0]     at Timer.listOnTimeout (timers.js:270:5)

As I need to wait for a thirdparty widget to load , this one fails at 20000. Could you let me know how to fix this?

**Comment by inspiraller** [comment]
Hi. I can look later tonight in more detail but for now experiment changing wdio.config, any of the timeouts. 
``` waitforTimeout: 1000000
```
Or 
```
cucumberOpts:{...timeout:1000000}
```

**Comment by inspiraller** [comment]
```
waitForTimout: 10000000
```

**Comment by inspiraller** [comment]
Sorry. its wdio.conf.js

**Comment by id4automation** [comment]
Thanks for the response. Even after updating the wdio.conf.js with the value,it retains the old value 20000.  Hence, it's throwing the same error when I try with the new value 

> waitForTimout: 10000000

**Comment by id4automation** [comment]
This is working after updating the cucumberOpt.
